# Generated by Django 2.2.5 on 2019-11-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountRequest',
        ),
    ]
