# Generated by Django 2.2 on 2019-07-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190401_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cat',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
