# Generated by Django 2.2 on 2019-07-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cat',
        ),
    ]
