# Generated by Django 2.2.5 on 2019-11-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='keep_account',
            field=models.BooleanField(default=False),
        ),
    ]
