# Generated by Django 3.2.9 on 2021-11-27 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211127_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusernote',
            old_name='user',
            new_name='customuser',
        ),
        migrations.AddField(
            model_name='customusernote',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customusernote',
            name='note',
            field=models.TextField(default='thenote'),
            preserve_default=False,
        ),
    ]
