# Generated by Django 3.2.9 on 2021-11-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20211127_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserNote',
        ),
    ]
