# Generated by Django 2.2 on 2019-04-01 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(blank=True, max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('aka', models.CharField(blank=True, max_length=50, verbose_name='AKA')),
                ('old_id', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('date_added', models.DateField(auto_now=True)),
                ('has_image', models.BooleanField(default=False)),
                ('image_checked', models.BooleanField(default=False)),
                ('has_details', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'alumni',
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('alumnus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alumnus')),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Section')),
            ],
        ),
    ]
