# Generated by Django 2.2 on 2019-04-01 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_duespayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnusNickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=25)),
                ('alumnus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alumnus')),
            ],
        ),
    ]
