# Generated by Django 2.2 on 2019-04-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alumnusnickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnusnickname',
            name='alumnus',
        ),
        migrations.AddField(
            model_name='alumnusnickname',
            name='old_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
