# Generated by Django 2.2 on 2019-04-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190401_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStartTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.PositiveIntegerField(default=0)),
                ('team_start', models.PositiveIntegerField(default=0)),
                ('team_end', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
