# Generated by Django 2.2 on 2019-04-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_honorary'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnus',
            name='honorary_gk',
            field=models.BooleanField(default=False),
        ),
    ]
