# Generated by Django 2.2 on 2019-04-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alumnus_honorary_gk'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorary',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamstarttwo',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
