# Generated by Django 2.2 on 2019-04-01 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_alumnus_date_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlumnusNickname',
        ),
    ]
