# Generated by Django 2.2 on 2019-04-01 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_alumnusnickname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamStartTwo',
            new_name='TeamDate',
        ),
    ]
