# Generated by Django 2.2 on 2019-04-01 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190401_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamdate',
            old_name='team_end',
            new_name='team_end_one',
        ),
        migrations.RenameField(
            model_name='teamdate',
            old_name='team_start',
            new_name='team_start_one',
        ),
    ]
