# Generated by Django 2.2 on 2019-04-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190401_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdate',
            name='team_end_two',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamdate',
            name='team_start_two',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
