# Generated by Django 2.2 on 2019-04-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190401_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdate',
            name='team_end_one',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='teamdate',
            name='team_end_two',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='teamdate',
            name='team_start_one',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='teamdate',
            name='team_start_two',
            field=models.CharField(max_length=4),
        ),
    ]
