# Generated by Django 2.2 on 2019-04-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190401_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnus',
            name='hide_from_roster',
            field=models.BooleanField(default=False),
        ),
    ]
