# Generated by Django 2.2 on 2019-04-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
