# Generated by Django 2.2 on 2019-04-02 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_contactrequest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
