# Generated by Django 2.2 on 2019-04-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_issues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issues',
            new_name='Issue',
        ),
    ]
