# Generated by Django 2.2 on 2019-04-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_issue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedate',
            name='test_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
