# Generated by Django 2.2 on 2019-04-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_servicedate_test_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedate',
            name='test_end_date',
        ),
    ]
