# Generated by Django 2.2 on 2019-04-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_servicedate_test_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedate',
            name='test_end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
