# Generated by Django 2.2 on 2019-04-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_servicedate_test_end_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicedate',
            old_name='test_end_year',
            new_name='end_year',
        ),
    ]
