# Generated by Django 2.2 on 2019-04-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20190406_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedate',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
