# Generated by Django 2.2 on 2019-04-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alumnus_search_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='search_field',
            field=models.TextField(editable=False),
        ),
    ]
