# Generated by Django 2.2 on 2019-04-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20190407_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='url',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
