# Generated by Django 2.2 on 2019-07-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_contactrequest_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email_address', models.EmailField(max_length=150)),
                ('dues_paid', models.BooleanField(default=0)),
            ],
        ),
    ]
