# Generated by Django 2.2 on 2019-07-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_registration_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='type',
            field=models.IntegerField(choices=[(1, 'Alumnus'), (2, 'Current'), (3, 'Honorary'), (4, 'Other')], default=1),
            preserve_default=False,
        ),
    ]
