# Generated by Django 2.2 on 2019-07-13 08:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_registration_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_veggie', models.BooleanField(default=False)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Registration')),
            ],
        ),
    ]
