# Generated by Django 2.2 on 2019-07-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_registrationguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationguest',
            name='event',
            field=models.IntegerField(choices=[(1, 'Friday Night'), (2, 'Saturday')], default=1),
            preserve_default=False,
        ),
    ]
