# Generated by Django 2.2 on 2019-07-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_registrationguest_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationguest',
            name='event',
            field=models.IntegerField(choices=[(1, 'Friday Night'), (2, 'Saturday Night')]),
        ),
    ]
