# Generated by Django 2.2 on 2019-07-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20190713_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationguest',
            name='event',
        ),
    ]
