# Generated by Django 2.2 on 2019-07-13 09:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_registration_num_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('event', models.IntegerField(choices=[(1, 'Friday Night'), (2, 'Saturday Night')])),
                ('is_veggie', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Registration')),
            ],
        ),
    ]
