# Generated by Django 2.2 on 2019-07-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_attendee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationGuest',
        ),
    ]
