# Generated by Django 2.2 on 2019-07-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_delete_registrationguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
