# Generated by Django 2.2 on 2019-07-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_registration_stripe_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
