# Generated by Django 2.2 on 2019-07-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
