# Generated by Django 2.2 on 2019-07-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_sponsorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=150),
        ),
    ]
