# Generated by Django 2.2 on 2019-07-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20190715_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='date_used',
            field=models.DateField(blank=True, null=True),
        ),
    ]
