# Generated by Django 2.2 on 2019-07-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20190715_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='num_veggie',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
