# Generated by Django 2.2 on 2019-07-16 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_registration_num_veggie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='is_veggie',
        ),
    ]
