# Generated by Django 2.2 on 2019-07-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alumnus_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnus',
            name='user',
        ),
    ]
