# Generated by Django 2.2 on 2019-07-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_remove_alumnus_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='dues_paid',
        ),
    ]
