# Generated by Django 2.2 on 2019-07-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20190721_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.IntegerField(choices=[(1, 'Alumnus/Alumnae'), (2, 'Current Team Member'), (3, 'Honorary GK')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='old_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
