# Generated by Django 2.2 on 2019-07-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_profile_mos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamDate',
            new_name='TeamDateOld',
        ),
    ]
