# Generated by Django 2.2 on 2019-07-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20190721_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Section')),
            ],
        ),
    ]
