# Generated by Django 2.2 on 2019-07-22 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_teamdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Registration')),
            ],
        ),
    ]
