# Generated by Django 2.2 on 2019-07-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_registrationnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationnote',
            name='note',
            field=models.TextField(),
        ),
    ]
