# Generated by Django 2.2 on 2019-08-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_auto_20190801_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='army_highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='civilian_highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_status',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team_highlights',
            field=models.TextField(blank=True),
        ),
    ]
