# Generated by Django 2.2 on 2019-08-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_oldprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldprofile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=250),
        ),
    ]
