# Generated by Django 2.2 on 2019-08-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20190801_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldprofile',
            name='army_beats',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='oldprofile',
            name='army_jobs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='oldprofile',
            name='awards',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='oldprofile',
            name='civilian_beats',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='oldprofile',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='oldprofile',
            name='current_status',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='oldprofile',
            name='license',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='oldprofile',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='oldprofile',
            name='team_beats',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='oldprofile',
            name='team_jobs',
            field=models.TextField(blank=True),
        ),
    ]
