# Generated by Django 2.2 on 2019-08-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_auto_20190802_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldprofile',
            name='army_beats',
            field=models.TextField(blank=True),
        ),
    ]
