# Generated by Django 2.2 on 2019-08-02 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_oldprofile_army_beats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldprofile',
            name='army_beats',
        ),
    ]
