# Generated by Django 2.2 on 2019-08-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_remove_oldprofile_army_beats'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldprofile',
            name='aka',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='aoy1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='aoy2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='army_beats',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='army_end_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='army_jobs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='army_start_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='awards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='civilian_beats',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='coy1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='coy2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='current_status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='deceased',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='goy1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='goy2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='hgk',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='hometown',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='license',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='poy1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='poy2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='rank',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='team_beats',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='team_end_one',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='team_end_two',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='team_jobs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='team_start_one',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='team_start_two',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='oldprofile',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
