# Generated by Django 2.2 on 2019-08-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_auto_20190802_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('profile_id', models.CharField(max_length=15)),
                ('notes', models.TextField()),
            ],
        ),
    ]
