# Generated by Django 2.2 on 2019-08-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_auto_20190804_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
