# Generated by Django 2.2 on 2019-08-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_profile_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deceased_year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
