# Generated by Django 2.2 on 2019-08-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_profile_deceased_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='army_end_date',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='army_start_date',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
