# Generated by Django 2.2 on 2019-08-04 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_auto_20190804_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldprofile',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Profile'),
        ),
    ]
