# Generated by Django 2.2 on 2019-08-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_oldprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='army_end_date',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='army_start_date',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
