# Generated by Django 2.2 on 2019-08-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_auto_20190805_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='deceased_year',
        ),
    ]
