# Generated by Django 2.2 on 2019-08-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_profile_army_highlights_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='civilian_highlights_old',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_status_old',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='team_highlights_old',
            field=models.TextField(blank=True),
        ),
    ]
