# Generated by Django 2.2 on 2019-08-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_auto_20190805_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfTheYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Golden Knight'), (2, 'Aviator'), (3, 'Photographer'), (4, 'Civilian')])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Registration')),
            ],
        ),
    ]
