# Generated by Django 2.2 on 2019-08-05 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_oftheyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oftheyear',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Profile'),
        ),
    ]
