# Generated by Django 2.2 on 2019-08-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0088_armyhighlight_civilianhighlight_teamhighlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armyhighlight',
            name='text',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='civilianhighlight',
            name='text',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='teamhighlight',
            name='text',
            field=models.CharField(max_length=150),
        ),
    ]
