# Generated by Django 2.2 on 2019-08-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_auto_20190806_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='army_highlights',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='civilian_highlights',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='team_highlights',
        ),
    ]
