# Generated by Django 2.2 on 2019-08-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_profile_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
