# Generated by Django 2.2 on 2019-08-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_profile_gkas_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gkas_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
