# Generated by Django 2.2 on 2019-08-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_auto_20190827_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='text',
            field=models.CharField(max_length=250),
        ),
    ]
