# Generated by Django 2.2.5 on 2019-09-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0104_profileimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='profile',
        ),
    ]
