# Generated by Django 2.2.5 on 2019-09-12 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0106_auto_20190912_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='profile',
            field=models.ForeignKey(default=368, on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
            preserve_default=False,
        ),
    ]
