# Generated by Django 2.2.5 on 2019-09-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0107_profileimage_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
