# Generated by Django 2.2.5 on 2019-09-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0108_auto_20190912_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
