# Generated by Django 2.2.5 on 2019-09-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0109_profileimage_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='name',
        ),
    ]
