# Generated by Django 2.2.5 on 2019-09-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_remove_profileimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='credit',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
