# Generated by Django 2.2.5 on 2019-09-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0111_auto_20190913_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=15)),
                ('short_name', models.CharField(max_length=2)),
            ],
        ),
    ]
