# Generated by Django 2.2.5 on 2019-10-04 05:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0112_shipstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.FileField(),
        ),
    ]
