# Generated by Django 2.2.5 on 2019-10-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0115_profileimage_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamdate',
            options={'ordering': ('start_year',)},
        ),
        migrations.AddField(
            model_name='profileimage',
            name='profile_image',
            field=models.BooleanField(default=False),
        ),
    ]
