# Generated by Django 2.2.5 on 2019-10-04 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0116_auto_20191004_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileimage',
            options={'ordering': ('-profile_id',)},
        ),
        migrations.AddField(
            model_name='profileimage',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
