# Generated by Django 2.2.5 on 2019-10-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0117_auto_20191004_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileimage',
            options={'ordering': ('-profile_image',)},
        ),
        migrations.AddField(
            model_name='highlight',
            name='home_page',
            field=models.BooleanField(default=False),
        ),
    ]
