# Generated by Django 2.2.5 on 2019-10-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0118_auto_20191005_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='homestate',
            new_name='home_state',
        ),
    ]
