# Generated by Django 2.2.5 on 2019-10-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0119_auto_20191006_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='home_city',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
