# Generated by Django 2.2.5 on 2019-10-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0120_profile_home_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='short_code',
            field=models.CharField(default='123fghjk', max_length=8),
            preserve_default=False,
        ),
    ]
