# Generated by Django 2.2.5 on 2019-10-12 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0122_auto_20191006_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdate',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Section'),
        ),
    ]
