# Generated by Django 2.2.5 on 2019-10-16 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0123_auto_20191012_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Team Highlight'), (3, 'Army Highlight'), (3, 'Civilian Highlight')])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
            ],
        ),
    ]
