# Generated by Django 2.2.5 on 2019-10-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0126_auto_20191016_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skip_state',
            field=models.BooleanField(default=False),
        ),
    ]
