# Generated by Django 2.2.5 on 2019-10-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0127_profile_skip_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='uuid',
        ),
    ]
