# Generated by Django 2.2.5 on 2019-10-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0129_profile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_cleaned',
            field=models.BooleanField(default=False),
        ),
    ]
