# Generated by Django 2.2.5 on 2019-10-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0132_profilenote_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='type',
            field=models.IntegerField(choices=[(0, 'Team Highlight'), (1, 'Army Highlight'), (2, 'Civilian Highlight'), (3, 'Licenses & Ratings'), (4, 'Awards & Badges')], default=0),
        ),
    ]
