# Generated by Django 2.2.5 on 2019-11-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0133_auto_20191018_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
