# Generated by Django 2.2.5 on 2019-11-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0136_auto_20191102_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='do_not_display',
            field=models.BooleanField(default=False),
        ),
    ]
