# Generated by Django 2.2.5 on 2019-11-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0137_profile_do_not_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='search_field',
            field=models.TextField(blank=True),
        ),
    ]
