# Generated by Django 2.2.5 on 2019-11-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0138_profile_search_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
