# Generated by Django 2.2.5 on 2019-11-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0139_highlight_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ('sort_order',)},
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='home_page',
        ),
    ]
