# Generated by Django 2.2.5 on 2019-11-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0140_auto_20191111_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email_address', models.EmailField(max_length=254)),
                ('info', models.TextField()),
            ],
        ),
    ]
