# Generated by Django 2.2.5 on 2019-11-14 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0141_accountrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
