# Generated by Django 2.2.5 on 2019-11-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0142_accountrequest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='name',
        ),
    ]
