# Generated by Django 2.2.5 on 2019-11-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0146_originaluser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='olduser',
            old_name='profile_id',
            new_name='member_id',
        ),
    ]
