# Generated by Django 2.2.5 on 2019-11-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0147_auto_20191125_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='olduser',
            name='profile_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
