# Generated by Django 2.2.5 on 2019-11-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0148_olduser_profile_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldUser',
        ),
    ]
