# Generated by Django 2.2.5 on 2019-11-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0149_delete_olduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='originaluser',
            name='type',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
