# Generated by Django 2.2.5 on 2019-11-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0153_auto_20191127_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
