# Generated by Django 2.2.5 on 2019-11-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0154_gallery_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True)),
                ('credit', models.CharField(blank=True, max_length=150)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('old_id', models.CharField(max_length=32)),
            ],
        ),
    ]
