# Generated by Django 2.2.5 on 2019-11-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0156_auto_20191127_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldgalleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
