# Generated by Django 2.2.5 on 2019-11-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0158_oldgalleryimage_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldgalleryimage',
            name='transferred',
            field=models.BooleanField(default=False),
        ),
    ]
