# Generated by Django 2.2.5 on 2019-11-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0160_galleryimage_has_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='has_image',
        ),
    ]
