# Generated by Django 2.2.5 on 2019-12-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0163_galleryimagesearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpayment',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
