# Generated by Django 2.2.5 on 2019-12-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0164_donationpayment_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('contact', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
