# Generated by Django 2.2.5 on 2019-12-04 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0165_registrationtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.RegistrationTable'),
        ),
    ]
