# Generated by Django 2.2.5 on 2019-12-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0166_registration_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='registration',
            new_name='registration_table',
        ),
    ]
