# Generated by Django 2.2.5 on 2019-12-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0167_auto_20191204_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationtable',
            name='number',
        ),
    ]
