# Generated by Django 2.2.5 on 2019-12-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0168_remove_registrationtable_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='registration',
            name='email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
