# Generated by Django 2.2.5 on 2020-03-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0169_auto_20191205_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={},
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='donationpayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='duespayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='text',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='issue',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registrationnote',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
