# Generated by Django 2.2.5 on 2020-03-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0173_auto_20200307_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestory',
            name='snippet',
            field=models.CharField(default='snippet', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilestory',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
