# Generated by Django 2.2.5 on 2020-03-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0174_auto_20200307_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestory',
            name='short_code',
            field=models.CharField(default='code', max_length=8),
            preserve_default=False,
        ),
    ]
