# Generated by Django 2.2.5 on 2020-03-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0179_auto_20200308_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp_user_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
