# Generated by Django 2.2.5 on 2020-03-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0181_profile_has_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='thumbnail_checked',
            field=models.BooleanField(default=False),
        ),
    ]
