# Generated by Django 2.2.5 on 2020-03-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0182_profile_thumbnail_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='d_number',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
