# Generated by Django 2.2.5 on 2020-03-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0183_profile_d_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='d_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
