# Generated by Django 2.2.5 on 2020-03-12 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0186_armyjob_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armyjob',
            options={'ordering': ('sort_order',)},
        ),
    ]
