# Generated by Django 2.2.5 on 2020-03-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0187_auto_20200312_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AddField(
            model_name='award',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
