# Generated by Django 2.2.5 on 2020-03-12 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0188_auto_20200312_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('type', models.IntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
    ]
