# Generated by Django 2.2.5 on 2020-03-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0189_profileentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileentry',
            name='link',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
