# Generated by Django 2.2.5 on 2020-03-13 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0190_profileentry_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Highlight',
        ),
    ]
