# Generated by Django 2.2.5 on 2020-03-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0191_delete_highlight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArmyJob',
        ),
    ]
