# Generated by Django 2.2.5 on 2020-03-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0192_delete_armyjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Award',
        ),
    ]
