# Generated by Django 2.2.5 on 2020-03-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0193_delete_award'),
    ]

    operations = [
        migrations.DeleteModel(
            name='License',
        ),
    ]
