# Generated by Django 2.2.5 on 2020-03-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0194_delete_license'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddInfo',
        ),
    ]
