# Generated by Django 2.2.5 on 2020-03-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0195_delete_addinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
