# Generated by Django 2.2.5 on 2020-03-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0196_delete_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamHighlight',
        ),
    ]
