# Generated by Django 2.2.5 on 2020-03-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0197_delete_teamhighlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilianhighlight',
            name='profile',
        ),
        migrations.DeleteModel(
            name='ArmyHighlight',
        ),
        migrations.DeleteModel(
            name='CivilianHighlight',
        ),
    ]
