# Generated by Django 2.2.5 on 2020-03-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0198_auto_20200313_0802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Honorary',
        ),
    ]
