# Generated by Django 2.2.5 on 2020-03-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0199_delete_honorary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceDate',
        ),
    ]
