# Generated by Django 2.2.5 on 2020-03-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0200_delete_servicedate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumnus',
        ),
    ]
