# Generated by Django 2.2.5 on 2020-03-13 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0201_delete_alumnus'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
