# Generated by Django 2.2.5 on 2020-03-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0203_profileimage_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileimage',
            options={'ordering': ('-profile_image', 'sort_order')},
        ),
    ]
