# Generated by Django 2.2.5 on 2020-03-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0204_auto_20200313_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='date_inactive',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
