# Generated by Django 2.2.5 on 2020-03-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0205_profileimage_date_inactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='date_inactive',
            new_name='date_delete',
        ),
    ]
