# Generated by Django 3.0.4 on 2020-03-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0207_profileimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldhighlight',
            name='type',
        ),
    ]
