# Generated by Django 3.0.4 on 2020-03-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0209_auto_20200314_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldhighlight',
            name='slug',
            field=models.SlugField(default='the-slug'),
            preserve_default=False,
        ),
    ]
