# Generated by Django 3.0.4 on 2020-03-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0210_oldhighlight_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_highlights',
            field=models.BooleanField(default=False),
        ),
    ]
