# Generated by Django 3.0.4 on 2020-03-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0211_profile_old_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url_code',
            field=models.CharField(default='smitty', max_length=15),
            preserve_default=False,
        ),
    ]
