# Generated by Django 3.0.4 on 2020-03-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0213_profileentry_date_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
