# Generated by Django 3.0.4 on 2020-03-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0214_auto_20200315_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
