# Generated by Django 3.0.4 on 2020-03-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0216_profileactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileactivity',
            name='type',
            field=models.SlugField(default='highlight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileactivity',
            name='type_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
