# Generated by Django 3.0.4 on 2020-03-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0217_auto_20200316_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileentry',
            name='type',
            field=models.IntegerField(choices=[(1, 'Highlight'), (2, 'Army Job'), (3, 'Award or Badge'), (4, 'License or Badge'), (5, 'Additional Info'), (6, 'External Link'), (7, 'Admin Note')], default=1),
        ),
    ]
