# Generated by Django 3.0.4 on 2020-03-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0219_profileentry_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='update_priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
