# Generated by Django 3.0.4 on 2020-03-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0220_profile_update_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='update_complete',
            field=models.BooleanField(default=False),
        ),
    ]
