# Generated by Django 3.0.4 on 2020-04-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0221_profile_update_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileentry',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profileentry',
            name='type',
            field=models.IntegerField(choices=[(1, 'Team Job'), (2, 'Army Job'), (3, 'Award or Badge'), (4, 'License or Badge'), (5, 'Additional Info'), (6, 'External Link'), (7, 'Admin Note')], default=1),
        ),
    ]
