# Generated by Django 3.0.4 on 2020-08-03 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0222_auto_20200401_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profileentry',
            name='type',
            field=models.IntegerField(choices=[(1, 'Team Job'), (2, 'Army Job'), (3, 'Award or Badge'), (4, 'License or Badge'), (5, 'Highlight'), (6, 'Comment or Story'), (7, 'External Link'), (8, 'Admin Note')], default=1),
        ),
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
            ],
        ),
    ]
