# Generated by Django 3.0.4 on 2020-08-03 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0224_subeventpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='subeventpricing',
            name='cutoff_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
