# Generated by Django 3.0.4 on 2020-08-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0225_subeventpricing_cutoff_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subevent',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='subeventpricing',
            options={'ordering': ('cutoff_date',)},
        ),
        migrations.AddField(
            model_name='subeventpricing',
            name='type',
            field=models.IntegerField(choices=[(1, 'Alumnus'), (2, 'Current'), (3, 'Honorary'), (4, 'Other')], default=0),
        ),
    ]
