# Generated by Django 3.0.4 on 2020-08-03 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0226_auto_20200803_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subeventpricing',
            options={'ordering': ('type', 'cutoff_date')},
        ),
        migrations.AlterField(
            model_name='subeventpricing',
            name='type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Alumnus'), (2, 'Current'), (3, 'Honorary'), (4, 'Other')], default=0),
        ),
        migrations.CreateModel(
            name='SubEventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SubEvent')),
            ],
        ),
        migrations.CreateModel(
            name='SubEventAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('each', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SubEventRegistration')),
            ],
        ),
    ]
