# Generated by Django 3.0.4 on 2020-08-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0227_auto_20200803_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='subeventregistration',
            name='type',
            field=models.IntegerField(choices=[(1, 'Alumnus'), (2, 'Current'), (3, 'Honorary'), (4, 'Other')], default=1),
            preserve_default=False,
        ),
    ]
