# Generated by Django 3.0.4 on 2020-08-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0228_subeventregistration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_code',
            field=models.CharField(default='12345678', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subevent',
            name='short_code',
            field=models.CharField(default='hrt4kng9', max_length=8),
            preserve_default=False,
        ),
    ]
