# Generated by Django 3.0.4 on 2020-08-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0229_auto_20200804_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='subeventregistration',
            name='quantity',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
