# Generated by Django 3.0.4 on 2020-08-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0230_subeventregistration_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='subeventregistration',
            name='short_code',
            field=models.CharField(default='rge3jb9s', max_length=8),
            preserve_default=False,
        ),
    ]
