# Generated by Django 3.0.4 on 2020-08-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0232_registrationpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subeventregistration',
            name='total',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
            preserve_default=False,
        ),
    ]
