# Generated by Django 3.0.4 on 2020-08-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0233_subeventregistration_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subeventregistration',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
