# Generated by Django 3.0.4 on 2020-08-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0234_auto_20200811_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationPayment',
        ),
    ]
