# Generated by Django 3.0.4 on 2020-08-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0235_delete_registrationpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2020-11-05'),
            preserve_default=False,
        ),
    ]
