# Generated by Django 3.0.4 on 2020-08-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0236_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cutoff_date', models.DateField()),
                ('type', models.IntegerField(choices=[(0, 'None'), (1, 'Alumnus'), (2, 'Current'), (3, 'Honorary'), (4, 'Other')], default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
            ],
            options={
                'ordering': ('type', 'cutoff_date'),
            },
        ),
    ]
