# Generated by Django 3.0.4 on 2020-08-11 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0237_eventpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(1, 'Alumnus'), (2, 'Current'), (3, 'Honorary'), (4, 'Other')])),
                ('quantity', models.PositiveIntegerField()),
                ('short_code', models.CharField(max_length=8)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
            ],
        ),
    ]
