# Generated by Django 3.0.4 on 2020-08-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0238_eventregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subeventattendee',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='subeventpricing',
            name='subevent',
        ),
        migrations.RemoveField(
            model_name='subeventregistration',
            name='subevent',
        ),
        migrations.DeleteModel(
            name='SubEvent',
        ),
        migrations.DeleteModel(
            name='SubEventAttendee',
        ),
        migrations.DeleteModel(
            name='SubEventPricing',
        ),
        migrations.DeleteModel(
            name='SubEventRegistration',
        ),
    ]
