# Generated by Django 3.0.4 on 2020-08-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0239_auto_20200811_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='add_dues',
            field=models.BooleanField(default=False),
        ),
    ]
