# Generated by Django 3.0.4 on 2020-08-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0242_auto_20200812_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='charge_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
