# Generated by Django 3.0.4 on 2020-08-12 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0244_auto_20200812_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cutoff_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
