# Generated by Django 3.0.4 on 2020-08-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0246_event_door_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='test_mode',
            field=models.BooleanField(default=True),
        ),
    ]
