# Generated by Django 3.0.4 on 2020-09-15 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0250_duespayment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='duespayment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
    ]
