# Generated by Django 3.0.4 on 2020-10-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0251_duespayment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='thumb',
            field=models.BooleanField(default=False),
        ),
    ]
