# Generated by Django 3.0.4 on 2021-08-03 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0254_subevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subevent',
            name='amount',
        ),
        migrations.CreateModel(
            name='SubEventPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.IntegerField(choices=[(1, 'Alumnus'), (2, 'Current'), (3, 'Honorary'), (4, 'Other')])),
                ('subevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SubEvent')),
            ],
            options={
                'ordering': ('type',),
            },
        ),
    ]
