# Generated by Django 3.0.4 on 2021-08-03 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0255_auto_20210803_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='add_dues',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='charge_id',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='each',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='name',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='refunded',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='short_code',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='total',
        ),
        migrations.CreateModel(
            name='EventRegistrationOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(1, 'Alumnus'), (2, 'Current'), (3, 'Honorary'), (4, 'Other')])),
                ('short_code', models.CharField(max_length=8)),
                ('quantity', models.PositiveIntegerField()),
                ('each', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('add_dues', models.BooleanField(default=False)),
                ('charge_id', models.CharField(blank=True, max_length=32)),
                ('refunded', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
            ],
        ),
    ]
