# Generated by Django 3.0.4 on 2021-08-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0257_subeventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='short_code',
            field=models.CharField(default='345678', max_length=8),
            preserve_default=False,
        ),
    ]
