# Generated by Django 3.0.4 on 2021-08-03 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0258_eventregistration_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subeventregistration',
            name='subevent',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.SubEvent'),
            preserve_default=False,
        ),
    ]
