# Generated by Django 3.0.4 on 2021-08-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0259_subeventregistration_subevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='name',
            field=models.CharField(default='Tom Hewitt', max_length=150),
            preserve_default=False,
        ),
    ]
