# Generated by Django 3.0.4 on 2021-08-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0260_eventregistration_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subeventpricing',
            name='add_ons',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subeventpricing',
            name='plus_one',
            field=models.BooleanField(default=False),
        ),
    ]
