# Generated by Django 3.0.4 on 2021-08-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0261_auto_20210803_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='subeventpricing',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
