# Generated by Django 3.0.4 on 2021-08-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0263_remove_subeventpricing_plus_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subeventregistration',
            name='each',
        ),
    ]
