# Generated by Django 3.0.4 on 2021-08-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0264_remove_subeventregistration_each'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subeventpricing',
            old_name='add_ons',
            new_name='add_on_pricing',
        ),
    ]
