# Generated by Django 3.0.4 on 2021-08-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0265_auto_20210803_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='subeventpricing',
            name='free_with_dues',
            field=models.BooleanField(default=False),
        ),
    ]
