# Generated by Django 3.0.4 on 2021-08-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0267_eventregistration_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
