# Generated by Django 3.0.4 on 2021-08-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0269_auto_20210810_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='dues_added',
            field=models.BooleanField(default=False),
        ),
    ]
