# Generated by Django 3.0.4 on 2021-11-03 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0271_recentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
