# Generated by Django 3.0.4 on 2021-11-04 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0272_profile_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentprofile',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='profileentry',
            name='type',
            field=models.IntegerField(choices=[(1, 'Team Job'), (2, 'Army Job'), (3, 'Award or Badge'), (4, 'License or Rating'), (5, 'Highlight'), (6, 'Comment or Story'), (7, 'External Link'), (8, 'Admin Note')], default=1),
        ),
        migrations.CreateModel(
            name='ProfileEntryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('singular', models.CharField(max_length=50)),
                ('profileentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProfileEntry')),
            ],
        ),
    ]
