# Generated by Django 3.0.4 on 2021-11-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0273_auto_20211104_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileentrytype',
            name='profileentry',
        ),
    ]
