# Generated by Django 3.0.4 on 2021-11-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0274_remove_profileentrytype_profileentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileEntryType',
            new_name='EntryType',
        ),
    ]
