# Generated by Django 3.0.4 on 2021-11-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0276_profileentry_entrytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrytype',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
