# Generated by Django 3.0.4 on 2021-11-11 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0278_armydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
