# Generated by Django 3.0.4 on 2021-11-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0279_accountrequest_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
