# Generated by Django 3.0.4 on 2021-11-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0280_auto_20211112_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
