# Generated by Django 3.0.4 on 2021-11-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0281_auto_20211112_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='year',
            field=models.CharField(blank=True, default='', max_length=4),
            preserve_default=False,
        ),
    ]
