# Generated by Django 3.0.4 on 2021-11-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0282_auto_20211112_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
