# Generated by Django 3.0.4 on 2021-11-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0283_profileimage_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gkas_year',
            field=models.CharField(blank=True, default='', max_length=4),
            preserve_default=False,
        ),
    ]
