# Generated by Django 3.0.4 on 2021-11-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0284_auto_20211112_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilestory',
            name='short_code',
        ),
        migrations.RemoveField(
            model_name='profilestory',
            name='snippet',
        ),
        migrations.AlterField(
            model_name='profilestory',
            name='title',
            field=models.CharField(blank=True, default='title', max_length=150),
            preserve_default=False,
        ),
    ]
