# Generated by Django 3.0.4 on 2021-11-14 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0287_remove_profileentryexample_profileentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileentryexample',
            name='entrytype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.EntryType'),
            preserve_default=False,
        ),
    ]
