# Generated by Django 3.0.4 on 2021-11-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0288_profileentryexample_entrytype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileEntryExample',
            new_name='EntryExample',
        ),
    ]
