# Generated by Django 3.0.4 on 2021-11-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0291_profilecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilecomment',
            old_name='date_added',
            new_name='date',
        ),
    ]
