# Generated by Django 3.0.4 on 2021-11-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0292_auto_20211115_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilecomment',
            options={'ordering': ('-date',)},
        ),
        migrations.DeleteModel(
            name='ProfileStory',
        ),
    ]
