# Generated by Django 3.0.4 on 2021-11-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0293_auto_20211115_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileentry',
            name='text',
            field=models.CharField(max_length=250),
        ),
    ]
