# Generated by Django 3.0.4 on 2021-11-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0295_auto_20211115_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileentry',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
