# Generated by Django 3.0.4 on 2021-11-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0297_profilestory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileComment',
        ),
    ]
