# Generated by Django 3.0.4 on 2021-11-18 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0298_delete_profilecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountrequest',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='duespayment',
            options={'ordering': ('-date',)},
        ),
        migrations.CreateModel(
            name='AccountRequestNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('reminder_date', models.DateField()),
                ('accountrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AccountRequest')),
            ],
        ),
    ]
