# Generated by Django 3.0.4 on 2021-11-18 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0300_auto_20211118_0625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountrequestnote',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='accountrequestnote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
