# Generated by Django 3.0.4 on 2021-11-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0302_auto_20211118_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='needs_vetting',
            field=models.BooleanField(default=False),
        ),
    ]
