# Generated by Django 3.0.4 on 2021-11-20 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0303_accountrequest_needs_vetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='accountrequest',
            options={'ordering': ('needs_vetting', '-date')},
        ),
        migrations.CreateModel(
            name='ProfileFilterHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
                ('profilefilter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProfileFilter')),
            ],
        ),
    ]
