# Generated by Django 3.0.4 on 2021-11-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0304_auto_20211120_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefilterholder',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
