# Generated by Django 3.0.4 on 2021-11-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0305_profilefilterholder_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefilter',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
