# Generated by Django 3.2.9 on 2021-11-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0307_profile_teamdate_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefilter',
            name='use_filter_date',
            field=models.BooleanField(default=False),
        ),
    ]
