# Generated by Django 3.2.9 on 2021-11-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0308_profilefilter_use_filter_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefilter',
            name='filter_date_title',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
