# Generated by Django 3.2.9 on 2021-11-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0309_profilefilter_filter_date_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefilter',
            name='filter_date_title',
        ),
    ]
