# Generated by Django 3.2.9 on 2021-11-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0310_remove_profilefilter_filter_date_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefilter',
            name='roster_card_title',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
