# Generated by Django 3.2.9 on 2021-11-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0311_profilefilter_roster_card_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefilter',
            name='roster_card_title',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
