# Generated by Django 3.2.9 on 2021-11-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0313_alter_profilefilter_roster_card_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImageHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gallery')),
                ('galleryimage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.galleryimage')),
            ],
        ),
    ]
