# Generated by Django 3.2.9 on 2021-11-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0314_galleryimageholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
