# Generated by Django 3.2.9 on 2021-11-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0316_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='old_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
