# Generated by Django 3.2.9 on 2021-11-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0320_profileimage_roster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_link',
            field=models.BooleanField(default=False),
        ),
    ]
