# Generated by Django 3.2.9 on 2021-11-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0323_profileupdate_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrequestnote',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
