# Generated by Django 3.2.9 on 2021-11-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0324_alter_accountrequestnote_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='pending_verification',
            field=models.BooleanField(default=False),
        ),
    ]
