# Generated by Django 3.2.9 on 2021-11-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0326_accountrequest_pending_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountrequest',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='accountrequest',
            name='needs_vetting',
        ),
    ]
