# Generated by Django 3.2.9 on 2021-11-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0327_auto_20211127_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='not_alumnus',
            field=models.BooleanField(default=False),
        ),
    ]
