# Generated by Django 3.2.9 on 2021-11-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0330_alter_profileupdate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='complete',
            field=models.DateTimeField(null=True),
        ),
    ]
