# Generated by Django 3.2.9 on 2021-11-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0332_auto_20211128_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
