# Generated by Django 3.2.9 on 2021-11-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0333_eventregistration_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='subeventregistration',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
