# Generated by Django 3.2.9 on 2021-11-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0337_remove_subeventregistration_checked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
    ]
