# Generated by Django 3.2.9 on 2021-12-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0338_eventregistration_emailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='closed_message',
            field=models.CharField(default='at the door', max_length=50),
            preserve_default=False,
        ),
    ]
