# Generated by Django 3.2.9 on 2021-12-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0339_event_closed_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='closed_message',
            field=models.CharField(max_length=60),
        ),
    ]
