# Generated by Django 3.2.9 on 2021-12-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0340_alter_event_closed_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
