# Generated by Django 3.2.9 on 2021-12-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0341_auto_20211201_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='comped',
            field=models.BooleanField(default=False),
        ),
    ]
