# Generated by Django 3.2.9 on 2022-05-21 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0344_auto_20220510_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registration_table',
        ),
    ]
