# Generated by Django 3.2.9 on 2022-05-21 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0345_remove_registration_registration_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationTable',
        ),
    ]
