# Generated by Django 3.2.9 on 2022-05-21 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0346_delete_registrationtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationNote',
        ),
    ]
