# Generated by Django 3.2.9 on 2022-05-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0347_delete_registrationnote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsorship',
        ),
    ]
