# Generated by Django 3.2.9 on 2022-05-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0348_delete_sponsorship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
