# Generated by Django 3.2.9 on 2022-05-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0349_delete_issue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
