# Generated by Django 3.2.13 on 2022-05-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0350_delete_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='event',
            new_name='revent',
        ),
    ]
