# Generated by Django 3.2.13 on 2022-05-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0352_rename_revent_attendee_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='event',
            field=models.IntegerField(choices=[(1, 'Friday Night'), (2, 'Saturday Night')], default=1),
        ),
    ]
