# Generated by Django 3.2.13 on 2022-05-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0355_alter_subeventpricing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='type',
            field=models.IntegerField(choices=[(1, 'Alumnus'), (2, 'Current'), (3, 'Honorary'), (4, 'Other')], default=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='type',
            field=models.IntegerField(choices=[(1, 'Alumnus'), (2, 'Current'), (3, 'Honorary'), (4, 'Other')], default=1),
        ),
    ]
