# Generated by Django 3.2.13 on 2022-05-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0356_auto_20220521_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oftheyear',
            name='type',
            field=models.IntegerField(choices=[(1, 'Golden Knight'), (2, 'Aviator'), (3, 'Photographer'), (4, 'Civilian')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.IntegerField(choices=[(1, 'Alumnus/Alumnae'), (2, 'Current Team Member'), (3, 'Honorary GK'), (5, 'Other')], default=1),
        ),
    ]
