# Generated by Django 3.2.16 on 2022-10-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0357_auto_20220521_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='subeventregistration',
            name='each',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
